#!/bin/bash
total 36
drwxr-xr-x 2 root root  206 Sep  4 10:46 .
drwxr-xr-x 6 root root  121 Sep  4 01:30 ..
-rw-r--r-- 1 root root   25 Sep  4 02:07 0-hello_world
-rw-r--r-- 1 root root   12 Sep  4 10:02 1-confused_smiley
-rw-r--r-- 1 root root 1338 Sep  4 10:09 2-hellofile
-rw-r--r-- 1 root root   12 Sep  4 10:17 3-twofiles
-rw-r--r-- 1 root root  663 Sep  4 10:28 4-lastlines
-rw-r--r-- 1 root root  436 Sep  4 10:32 5-firstlines
-rw-r--r-- 1 root root   12 Sep  4 10:34 6-third_line
-rw-r--r-- 1 root root   12 Sep  4 10:43 8-cwd_state
-rw-r--r-- 1 root root    0 Sep  4 10:46 ls_cwd_content
-rw-r--r-- 1 root root    6 Sep  4 10:42 README.md
